config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destory'

  namespace :admin do
    resources :users
  end

  root to: 'products#index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :kimonos, only: [ :index, :show ]

  get '/category/:category', to: 'kimonos#category'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  enum category:{unselected:0,hakama:1,furisode:2,houmongi:3}
  enum color:{unselected1:0,red:1,blue:2,brack:3,white:4,yellow:5,}
  enum scene:{unselected2:0,ceremony:1,wedding:2,party:3}
  validates :name, :description, presence: true, length: {minimum: 2 }
  # validates :image, file_size: { less_than_or_equal_to: 100.kilobytes }, file_content_type: { allow: ['image/jpeg', 'image/png'] }
  validates :price, numericality: { only_integer: true }
  validates :category, :color, :scene, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :tel, presence: true, numericality: { only_integer: true }
    validates :password, confirmation: true
    # validates :password_confirmation, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.first_name}」を登録しました。"
    else
      render :new
    end 
  end

  def update
    @user = User.find(params[:id])
  
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.first_name}」を更新しました。"
    else
      render :new
    end 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザー　「#{@user.first_name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :tel, :email, :admin, :password, :password_comfirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  
  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to= login_path unless current_user
  end
end

app/controllers/kimonos_controller.rb
class KimonosController < ApplicationController
  def index
    @hakamas = Product.where(category: '1').order(updated_at: 'desc').limit(3)
    @furisodes = Product.where(category: '2').order(updated_at: 'desc').limit(3)
    @houmongis = Product.where(category: '3').order(updated_at: 'desc').limit(3)
  end

  def show
    @hakamas = Product.find(params[:id])

  end

  def category
    @product_items = Product.where(category:params[:category])
    @category = params[:category]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "商品「#{@product.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update!(product_params)
    redirect_to products_url, notice: "商品「#{product.name}」を更新しました。"
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_url, notice: "商品「#{product.name}」を削除しました。"
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image, :price, :category, :color, :scene)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else 
      render :new
    end
  end

  def destory
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kimonos_helper.rb
module KimonosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.present? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [:admin, @user], local: true do |f| %>
　 <div class="form-group col-md-6">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', id: 'user_first_name' %>
　 </div>

　 <div class="form-group col-md-6">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', id: 'user_last_name' %>
　 </div>

　 <div class="form-group col-md-6">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control', id: 'user_address' %>
　 </div>

　 <div class="form-group col-md-6">
    <%= f.label :tel %>
    <%= f.text_field :tel, class: 'form-control', id: 'user_tel' %>
　 </div>

　 <div class="form-group col-md-6">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', id: 'user_email' %>
　 </div>

　 <div class="form-check">
    <%= f.check_box :admin, class: 'form-check-input' %>
    <%= f.label :admin, class: 'form-check-label' %>
　 </div>

　 <div class="form-group col-md-6">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
　 </div>

　 <div class="form-group ">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
　 </div>

　 <%= f.submit '登録する', class: 'btn btn-primary' %>

<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>

<div class="nav.justify-content-end">
  <%= link_to 'ユーザ一一覧', admin_users_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary' %> 

<div class="mb-3">
<table class="table table table-hover">
  <thead class="thead thead-default">
    <tr>
      <th><%= User.human_attribute_name(:first_name) %>
      <th><%= User.human_attribute_name(:last_name) %>
      <th><%= User.human_attribute_name(:address) %>
      <th><%= User.human_attribute_name(:tel) %>
      <th><%= User.human_attribute_name(:email) %>
      <th><%= User.human_attribute_name(:admin) %>
      <th><%= User.human_attribute_name(:created_at) %>
      <th><%= User.human_attribute_name(:updated_at) %>
      <th>
    </tr>
  </thead>
</div>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.first_name, [:admin,user] %>
        <td><%= user.last_name %>
        <td><%= user.address %>
        <td><%= user.tel %>
        <td><%= user.email %>
        <td><%= user.admin? ? 'あり' : 'なし' %>
        <td><%= user.created_at %>
        <td><%= user.updated_at %>
        <td>
          <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3' %>
          <%= link_to '削除', [:admin, user], method: :delete, data: { confirm: "タスク「#{user.first_name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>

<div class="nav-justify-content-end">
  <%= link_to 'ユーザ一覧', admin_users_path, class: 'nav-link' %>
</div> 

<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>

<div class="nav justify-content-end">
  <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' %>
</div>

<table class="table table table-hover">
  <tbody>
    <tr>
      <th><%= User.human_attribute_name(:id) %>
      <td><%= @user.id %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:first_name) %>
      <td><%= @user.first_name %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:last_name) %>
      <td><%= @user.last_name %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:address) %>
      <td><%= @user.address %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:tel) %>
      <td><%= @user.tel %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:email) %>
      <td><%= @user.email %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:admin) %>
      <td><%= @user.admin? ? 'あり' : 'なし' %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:created_at) %>
      <td><%= @user.created_at %>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:updated_at) %>
      <td><%= @user.updated_at %>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3' %>
<%= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "タスク「#{@user.first_name}」を削除しましす。よろしいですか？" }, class: 'btn btn-danger' %>

app/views/kimonos/category.html.erb
<h1><% if @category == "hakama"
     puts   </h1>
<tr>
  <th>Product.human_attribute_name(:image)</th>
</tr>

<tbody>
  <% @product_items.each do |product| %>
  
  <p><%= product.name %>
  </p>
  <p><%= product.image %>
  </p>
  <p><%= product.price %>
  </p>

  <% end %>
</tbody>

app/views/kimonos/index.html.erb
<h1>Kimono みなとや</h1>
<table>
  <thead>
    <tr>
      <th>Product.human_attribute_name(:image)</th>
    </tr>
  </thead>

  <tbody>
    <% @hakamas.each do |product| %>

        <section>
          <h2><a href=""><img src="images/category1.jpg" alt=""></a>
          </h2>
          <div class="listphoto">
            <!--★画像★-->
            <a href=""><%= product.image %><img src="" alt="" class="picture" decoding="async" />
            </a>
          </div>
          <div class="listrightbloc">
            <a href="<%= product_path(product) %>">
              <h3><%= product.name %></h3>
              <span><%= product.price %></span>
            </a>
          </div>
        </section>
    <% end %>
  </tbody>
<table>

<table>
  <thead>
    <tr>
      <th>Product.human_attribute_name(:image)</th>
    </tr>
  </thead>

  <tbody>
    <% @furisodes.each do |product| %>
      <tr>
        <td><%= product.image %></td>
      </tr>
    <% end %>
  </tbody>
<table>

<table>
  <thead>
    <tr>
      <th>Product.human_attribute_name(:image)</th>
    </tr>
  </thead>

  <tbody>
    <% @houmongis.each do |product| %>
      <tr>
        <td><%= product.image %></td>
      </tr>
    <% end %>
  </tbody>
<table>

app/views/kimonos/show.html.erb
<h1>Kimonos#show</h1>

<p><%= @hakamas.name %>
</p>
<p><%= @hakamas.description %>
</p>
<p><%= @hakamas.image %>
</p>
<p><%= @hakamas.price %>
</p>
<p><%= @hakamas.category %>
</p>
<p><%= @hakamas.color %>
</p>
<p><%= @hakamas.scene %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minatoya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="app-title navbar navbar-expand-md navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">KIMONO みなとや</span>
    </nav>

    <div class="container" >
      <% if flash.notice.present? %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<% if product.errors.present? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: product, local: true do |t| %>

    <div class="form-group col-md-6">
      <%= t.label :name %>
      <%= t.text_field :name, class: 'form-control', id: 'product_name' %>
    </div>

    <div class="form-group col-md-12">
      <%= t.label :description %>
      <%= t.text_area :description, class: 'form-control', id: 'product_description' %>
    </div>

    <div class="form-group col-md-6">
      <%= t.label :image %>
      <%= t.file_field :image, class: 'form-control-file', id: 'product_image' %>
    </div>

    <div class="form-group col-md-6">
      <%= t.label :price %>
      <%= t.text_field :price, class: 'form-control', id: 'product_price' %>
    </div>

    <div class="form-group col-md-6">
      <%= t.label :category %>
      <%= t.select :category, [["卒業式袴", :hakama], ["振袖", :furisode], ["訪問着", :houmongi]], {:include_blank => "選択メニュー"} %>
    </div>

    <div class="form-group col-md-6">
      <%= t.label :color %>
      <%= t.select :color, [["赤色", :red], ["青色", :blue], ["黒色", :black], ["白色", :white], ["黄色", :yellow]], {:include_blank => "選択メニュー"} %>
    </div>

    <div class="form-group col-md-6">
      <%= t.label :scene %>
      <%= t.select :scene, [["卒業式", :ceremony], ["結婚式", :wedding], ["パーティー",  :party]], {:include_blank => "選択メニュー"} %>
    </div>

    <%= t.submit nil, class: 'btn btn-primary' %>

  <% end %>

app/views/products/edit.html.erb
<h1>商品の編集</h1>

<div class="nav justify-content-end">
  <%= link_to '商品一覧', products_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { product: @product } %>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<%= link_to '新規登録', new_product_path, class: 'btn btn-primary' %> 

<div class="mb-3">
<table class="table table table-hover">
  <thead class="thead thead-default">
    <tr>
      <th><%= Product.human_attribute_name(:name) %>
      <th><%= Product.human_attribute_name(:image) %>
      <th><%= Product.human_attribute_name(:category) %>
      <th><%= Product.human_attribute_name(:created_at) %>
      <th>
    </tr>
  </thead>
</div>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %>
        <td><%= product.image %>
        <td><%= product.category %>
        <td><%= product.created_at %>
        <td>
          <%= link_to '編集', edit_product_path(product), class: 'btn btn-primary mr-3' %>
          <%= link_to '削除', product, method: :delete, data: { confirm: "商品「#{product.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>商品の新規登録</h1>

<div class="nav-justify-content-end">
  <%= link_to '商品一覧', products_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { product: @product } %>

app/views/products/show.html.erb
<h1>商品詳細</h1>

<div class="nav justify-content-end">
  <%= link_to '商品一覧', products_path, class: 'nav-link' %>
</div>

<table class="table table table-hover">
  <tbody>
    <tr>
      <th><%= Product.human_attribute_name(:id) %>
      <td><%= @product.id %>
    </tr>
    
    <tr>
      <th><%= Product.human_attribute_name(:name) %>
      <td><%= @product.name %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:description) %>
      <td><%= simple_format(h(@product.description), {}, sanitize: false, wrapper_tag: "div") %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:image) %>
      <td><%= image_tag @product.image if @product.image.attached? %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:price) %>
      <td><%= @product.price %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:color) %>
      <td><%= @product.color %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:scene) %>
      <td><%= @product.scene %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:created_at) %>
      <td><%= @product.created_at %>
    </tr>
    <tr>
      <th><%= Product.human_attribute_name(:updated_at) %>
      <td><%= @product.updated_at %>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_product_path, class: 'btn btn-primary mr-3' %>
<%= link_to '削除', @product, method: :delete, data: { confirm: "商品「#{@product.name}」を削除しましす。よろしいですか？" }, class: 'btn btn-danger' %>